services:
  app:
    image: analogic/poste.io
    container_name: mailserver
    hostname: mail
    domainname: obouhlel.xyz
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "143:143"
      - "993:993"
    volumes:
      - /opt/data/mail:/data
      - /opt/data/mail/webmail/plugins:/opt/www/webmail/plugins
      - /opt/data/mail/webmail/config:/opt/www/webmail/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Paris
      - HTTPS=OFF
      - VIRTUAL_HOST=mail.obouhlel.xyz
      - VIRTUAL_PORT=80
      - DISABLE_CLAMAV=FALSE
    restart: always

volumes:
  data:
    driver: local