version: "3.9"

services:
  mailserver:
    image: analogic/poste.io
    container_name: mailserver
    hostname: mail
    domainname: obouhlel.xyz
    restart: always
    networks:
      - coolify
    ports:
      - "25:25"      # SMTP (requis pour recevoir les mails)
      - "110:110"    # POP3
      - "143:143"    # IMAP
      - "587:587"    # SMTP Submission (clients)
      - "993:993"    # IMAPS
      - "995:995"    # POP3S
      - "4190:4190"  # Sieve (filtrage de mail, optionnel)
    environment:
      - TZ=Europe/Paris
    volumes:
      - /opt/data/mail:/data
      - /opt/data/mail/webmail/plugins:/opt/www/webmail/plugins
      - /opt/data/mail/webmail/config:/opt/www/webmail/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.posteio.rule=Host(`mail.obouhlel.xyz`)"
      - "traefik.http.routers.posteio.entrypoints=http,https"
      - "traefik.http.routers.posteio.tls=true"
      - "traefik.http.routers.posteio.tls.certresolver=letsencrypt"
      - "traefik.http.services.posteio.loadbalancer.server.port=80"
      - "traefik.http.middlewares.posteio-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.posteio-headers.headers.customrequestheaders.X-Forwarded-Ssl=on"
      - "traefik.http.routers.posteio.middlewares=posteio-headers"


networks:
  coolify:
    external: true
