services:
  app:
    image: analogic/poste.io
    container_name: mailserver
    hostname: mail
    domainname: obouhlel.xyz
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.posteio.rule=Host(`mail.obouhlel.xyz`)"
      - "traefik.http.routers.posteio.entrypoints=web"
      - "traefik.http.services.posteio.loadbalancer.server.port=80"
    volumes:
      - /opt/data/mail:/data
      - /opt/data/mail/webmail/plugins:/opt/www/webmail/plugins
      - /opt/data/mail/webmail/config:/opt/www/webmail/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Paris
      - HTTPS=OFF
      - DISABLE_CLAMAV=FALSE
    restart: always

networks:
  coolify:
    external: true

volumes:
  data:
    driver: local