version: "3.9"

services:
  mailserver:
    image: analogic/poste.io
    container_name: mailserver
    hostname: mail
    domainname: obouhlel.xyz
    restart: always
    networks:
      - coolify
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "587:587"
      - "993:993"
      - "995:995"
    environment:
      - TZ=Europe/Paris
      - DISABLE_CLAMAV=TRUE
      - DISABLE_LETSENCRYPT=TRUE 
    volumes:
      - /opt/data/mail:/data
      - /opt/data/mail/webmail/plugins:/opt/www/webmail/plugins
      - /opt/data/mail/webmail/config:/opt/www/webmail/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      
      # HTTP
      - "traefik.http.routers.mailserver.entrypoints=web"
      - "traefik.http.routers.mailserver.rule=Host(`mail.obouhlel.xyz`)"
      - "traefik.http.routers.mailserver.service=mailserver"
      - "traefik.http.services.mailserver.loadbalancer.server.port=80"
      
      # HTTPS
      - "traefik.http.routers.mailserver-secure.entrypoints=websecure"
      - "traefik.http.routers.mailserver-secure.rule=Host(`mail.obouhlel.xyz`)"
      - "traefik.http.routers.mailserver-secure.service=mailserver"
      - "traefik.http.routers.mailserver-secure.tls=true"
      - "traefik.http.routers.mailserver-secure.tls.certresolver=le"

      # Mail ports
      - "traefik.tcp.routers.smtp.entrypoints=smtp"
      - "traefik.tcp.routers.smtp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp.service=smtp"
      - "traefik.tcp.services.smtp.loadbalancer.server.port=25"

      - "traefik.tcp.routers.smtps.entrypoints=smtps"
      - "traefik.tcp.routers.smtps.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtps.service=smtps"
      - "traefik.tcp.services.smtps.loadbalancer.server.port=465"

networks:
  coolify:
    external: true
