services:
  app:
    image: analogic/poste.io
    container_name: mailserver
    hostname: mail
    domainname: obouhlel.xyz
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "143:143"
      - "993:993"
    volumes:
      - /opt/data/mail:/data
    environment:
      - TZ=Europe/Paris
      - HTTPS=ON
      - VIRTUAL_HOST=mail.obouhlel.xyz
    restart: always

volumes:
  data:
    driver: local