services:
  app:
    image: analogic/poste.io:latest
    container_name: posteio
    restart: always
    ports:
      - "25:25"
      - "587:587"
      - "993:993"
      - "80:80"
      - "443:443"
    environment:
      - DATA_DIR=/data
      - HTTPS=OFF
    volumes:
      - ./data:/data

volumes:
  data:
    driver: local